type ExportShot = {
  shotNumber: string;
  shotSize: string | null;
  cameraAngle: string | null;
  cameraMovement: string | null;
  lens: string | null;
  description: string;
  subjectOrFocus: string | null;
  notes: string | null;
};

type ExportSceneGroup = {
  scene: {
    sceneNumber: string;
    title: string | null;
    intExt: string | null;
    dayNight: string | null;
  };
  shots: ExportShot[];
};

function escapeCSV(value: string | null | undefined): string {
  if (!value) return "";
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function exportShotlistCSV(
  groups: ExportSceneGroup[],
  dayLabel: string
): void {
  const rows: string[] = [];
  rows.push(
    "Scene,Shot #,Size,Angle,Movement,Lens,Description,Subject,Notes"
  );

  for (const group of groups) {
    const sceneLabel = `${group.scene.sceneNumber}${group.scene.title ? ` - ${group.scene.title}` : ""}`;
    for (const shot of group.shots) {
      rows.push(
        [
          escapeCSV(sceneLabel),
          escapeCSV(shot.shotNumber),
          escapeCSV(shot.shotSize),
          escapeCSV(shot.cameraAngle),
          escapeCSV(shot.cameraMovement),
          escapeCSV(shot.lens),
          escapeCSV(shot.description),
          escapeCSV(shot.subjectOrFocus),
          escapeCSV(shot.notes)
        ].join(",")
      );
    }
  }

  const csv = rows.join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `shotlist-${dayLabel.replace(/\s+/g, "-").toLowerCase()}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

export function exportShotlistPrint(
  groups: ExportSceneGroup[],
  dayLabel: string
): void {
  let html = `<!DOCTYPE html>
<html>
<head>
<title>Shot List — ${dayLabel}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 11px; color: #111; padding: 20px; }
  h1 { font-size: 16px; margin-bottom: 4px; }
  .subtitle { font-size: 11px; color: #666; margin-bottom: 16px; }
  .scene-header { font-size: 13px; font-weight: 700; margin: 16px 0 6px; padding: 4px 0; border-bottom: 2px solid #111; }
  .scene-meta { font-weight: 400; color: #666; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
  th { text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; color: #666; border-bottom: 1px solid #ccc; padding: 3px 6px; }
  td { padding: 4px 6px; border-bottom: 1px solid #eee; vertical-align: top; }
  td.shot-num { font-family: monospace; font-weight: 600; white-space: nowrap; }
  td.size { white-space: nowrap; }
  td.movement { white-space: nowrap; color: #555; }
  td.lens { white-space: nowrap; color: #555; }
  td.subject { white-space: nowrap; color: #555; }
  td.notes { color: #555; font-style: italic; }
  .total { text-align: right; font-size: 10px; color: #666; margin-top: 16px; border-top: 1px solid #ccc; padding-top: 6px; }
  @media print {
    body { padding: 0; }
    .scene-header { break-after: avoid; }
    table { break-inside: auto; }
    tr { break-inside: avoid; }
  }
</style>
</head>
<body>
<h1>Shot List — ${dayLabel}</h1>
<p class="subtitle">${groups.reduce((s, g) => s + g.shots.length, 0)} shots across ${groups.length} scenes</p>
`;

  for (const group of groups) {
    const meta = [group.scene.intExt, group.scene.dayNight].filter(Boolean).join(" / ");
    html += `<div class="scene-header">Scene ${group.scene.sceneNumber}${group.scene.title ? ` — ${group.scene.title}` : ""} ${meta ? `<span class="scene-meta">${meta}</span>` : ""}</div>\n`;
    html += `<table>
<thead><tr><th>#</th><th>Size</th><th>Movement</th><th>Lens</th><th>Description</th><th>Subject</th><th>Notes</th></tr></thead>
<tbody>\n`;

    for (const shot of group.shots) {
      html += `<tr>
<td class="shot-num">${esc(shot.shotNumber)}</td>
<td class="size">${esc(shot.shotSize)}</td>
<td class="movement">${esc(shot.cameraMovement)}</td>
<td class="lens">${esc(shot.lens)}</td>
<td>${esc(shot.description)}</td>
<td class="subject">${esc(shot.subjectOrFocus)}</td>
<td class="notes">${esc(shot.notes)}</td>
</tr>\n`;
    }

    html += `</tbody></table>\n`;
  }

  html += `<p class="total">Generated by indieFilmer</p>
</body></html>`;

  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
  }
}

function esc(val: string | null | undefined): string {
  if (!val) return "—";
  return val.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
